export const PROPOSITIONS_LOADING = 'PROPOSITIONS_LOADING';
export const SAVE_PROPOSITIONS = 'SAVE_PROPOSITIONS';

export const USER_PROPOSALS_LOADING = 'USER_PROPOSALS_LOADING';
export const SAVE_USER_PROPOSALS = 'SAVE_USER_PROPOSALS';