export const AUTH_LOADING = 'AUTH_LOADING';

export const USER_LOADING = 'USER_LOADING';
export const SAVE_USER = 'SAVE_USER';

export const USER_SIGNING_UP = 'USER_SIGNING_UP';
export const NEW_USER_REGISTERED = 'NEW_USER_REGISTERED';

export const USER_CONFIRMING = 'USER_CONFIRMING';
export const USER_FORGOT_PASS_SENDING = 'USER_FORGOT_PASS_SENDING';
export const FORGOT_PASS_SEND_SUCCESS = 'USER_FORGOT_PASS_SENDING';

export const RESET_PASS_SUCCESS = 'RESET_PASS_SUCCESS';
export const RESET_PASS_LOADING = 'RESET_PASS_LOADING';

export const USERS_LOADING = 'USERS_LOADING';
export const SAVE_USERS = 'SAVE_USERS';